# Generated by Django 5.2.10 on 2026-01-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Grupo/Hospital')),
                ('mode', models.CharField(choices=[('SUPERVISED', 'Supervisionado'), ('SELF_MANAGED', 'Auto-Gerenciado')], default='SELF_MANAGED', max_length=20)),
                ('invite_token', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('duration', models.IntegerField(choices=[(6, '6 Horas'), (12, '12 Horas'), (24, '24 Horas')], default=12, verbose_name='Duração')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tradable', models.BooleanField(default=False, verbose_name='Disponível para Troca')),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantões',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Plantão')),
                ('color', models.CharField(default='#0d6efd', help_text='Ex: #FF0000 para vermelho', max_length=7, verbose_name='Cor (Hex)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente (Aguardando Dono)'), ('ACCEPTED_BY_OWNER', 'Aceito pelo Dono (Aguardando Admin)'), ('APPROVED', 'Aprovado e Finalizado'), ('REJECTED', 'Recusado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
