# Generated by Django 5.2.10 on 2026-01-22 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_groups', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='work_groups', to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
        migrations.AddField(
            model_name='shift',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='shift',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_types', to='shifts.group'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shifttype', verbose_name='Tipo de Plantão'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.group'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='offered_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_trade_requests', to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='target_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_trade_requests', to='shifts.shift'),
        ),
    ]
